version: '3.2'
volumes:
  postgres-data:
  bundler-cache:
services:
  db:
    image: postgres:alpine
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data:delegated
  app:
    build:
      context: .
      dockerfile: ./docker/app-dockerfile
    command: ''
    volumes:
    - .:/app:cached
    - bundler-cache:/usr/local/bundle:delegated
    working_dir: /app
    ports:
    - "3000:3000"
    depends_on:
    - db
    stdin_open: true
    tty: true
