version: '3.2'
volumes:
  postgres-data:
  bundler-cache:
services:
  redis-sidekiq:
    image: redis:alpine
    ports:
    - 127.0.0.1:6379:6379
  redis-rails:
    image: redis:alpine
    ports:
    - 127.0.0.1:6380:6379
  db:
    image: postgres:alpine
    ports:
    - 127.0.0.1:5432:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data:delegated
  app:
    build:
      context: .
      dockerfile: ./docker/app-dockerfile
    command: 'stubs/bundle exec sidekiq'
    volumes:
    - .:/app:cached
    - bundler-cache:/usr/local/bundle:delegated
    working_dir: /app
    ports:
    - 127.0.0.1:3000:3000
    depends_on:
    - db
    stdin_open: true
    tty: true
